// Code generated by "enumer -type SystemStatus -linecomment"; DO NOT EDIT.

package wifire

import (
	"fmt"
	"strings"
)

const (
	_SystemStatusName_0      = "ready"
	_SystemStatusLowerName_0 = "ready"
	_SystemStatusName_1      = "cooking"
	_SystemStatusLowerName_1 = "cooking"
	_SystemStatusName_2      = "offline"
	_SystemStatusLowerName_2 = "offline"
)

var (
	_SystemStatusIndex_0 = [...]uint8{0, 5}
	_SystemStatusIndex_1 = [...]uint8{0, 7}
	_SystemStatusIndex_2 = [...]uint8{0, 7}
)

func (i SystemStatus) String() string {
	switch {
	case i == 3:
		return _SystemStatusName_0
	case i == 6:
		return _SystemStatusName_1
	case i == 99:
		return _SystemStatusName_2
	default:
		return fmt.Sprintf("SystemStatus(%d)", i)
	}
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _SystemStatusNoOp() {
	var x [1]struct{}
	_ = x[StatusReady-(3)]
	_ = x[StatusCooking-(6)]
	_ = x[StatusOffline-(99)]
}

var _SystemStatusValues = []SystemStatus{StatusReady, StatusCooking, StatusOffline}

var _SystemStatusNameToValueMap = map[string]SystemStatus{
	_SystemStatusName_0[0:5]:      StatusReady,
	_SystemStatusLowerName_0[0:5]: StatusReady,
	_SystemStatusName_1[0:7]:      StatusCooking,
	_SystemStatusLowerName_1[0:7]: StatusCooking,
	_SystemStatusName_2[0:7]:      StatusOffline,
	_SystemStatusLowerName_2[0:7]: StatusOffline,
}

var _SystemStatusNames = []string{
	_SystemStatusName_0[0:5],
	_SystemStatusName_1[0:7],
	_SystemStatusName_2[0:7],
}

// SystemStatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func SystemStatusString(s string) (SystemStatus, error) {
	if val, ok := _SystemStatusNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _SystemStatusNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to SystemStatus values", s)
}

// SystemStatusValues returns all values of the enum
func SystemStatusValues() []SystemStatus {
	return _SystemStatusValues
}

// SystemStatusStrings returns a slice of all String values of the enum
func SystemStatusStrings() []string {
	strs := make([]string, len(_SystemStatusNames))
	copy(strs, _SystemStatusNames)
	return strs
}

// IsASystemStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i SystemStatus) IsASystemStatus() bool {
	for _, v := range _SystemStatusValues {
		if i == v {
			return true
		}
	}
	return false
}
